### ISSUE TITLE
R command error

### ISSUE THREAD

**Issue by tromika** [nuest/mro-docker#2]
Hi,

After a build or pull I got the error below when I'm running R command inside the container.
I know originally you solved https://github.com/RevolutionAnalytics/RRO/issues/265 but it seems I have the same problem.  

My docker version is 1.9.1 and I'm on Ubuntu 14.04.

```
dirname: missing operand
Try 'dirname --help' for more information.
dirname: missing operand
Try 'dirname --help' for more information.
/usr/bin/R: line 215: /etc/ldpaths: No such file or directory
ERROR: R_HOME ('') not found
```

**Comment by nuest** [comment]
Thanks for reporting. Could you paste a few more lines of the log, please? What is the last command that get's executed?

**Comment by tromika** [comment]
This is only what I got. I just run R and /usr/bin/R inside the container.

**Comment by tromika** [comment]
I found the problem. On server side I have AMD processors. I checked it on multiple AMD servers and MRO is somehow incompatible with AMD. It works smooth on any Intel powered machine.

**Comment by nuest** [comment]
Ah - OK. Did you find any documentation on the MRO website for that?
