### ISSUE TITLE
MKL does not seem to install correctly

### ISSUE THREAD

**Issue by jwainer** [nuest/mro-docker#4]
I ran the docker. 
It does not seems to install the MKL library correctly. 
If I install from within the docker it seems to work ok.

1) 
docker run -it nuest/docker-mro /bin/bash
root@ff955b433352:/home/docker# R

R version 3.2.3 (2015-12-10) -- "Wooden Christmas-Tree"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
...

Microsoft R Open 3.2.3
Default CRAN mirror snapshot taken on 2016-01-01
The enhanced R distribution from Microsoft
Visit http://go.microsoft.com/fwlink/?LinkID=722555 for information
about additional features.

No performance acceleration libraries were detected. To take advantage of 
the available processing power, also install MKL for MRO 3.2.3. Visit 
http://go.microsoft.com/fwlink/?LinkID=698301 for more details.

2) root@cadf33f01229:/home/docker# curl -LO -# https://mran.revolutionanalytics.com/install/mro/$MRO_VERSION/RevoMath-$MRO_VERSION.tar.gz
###### ################################################################## 100.0%

root@cadf33f01229:/home/docker# tar -xzf RevoMath-3.2.3.tar.gz 
root@cadf33f01229:/home/docker# cd RevoMath
root@cadf33f01229:/home/docker/RevoMath# ./RevoMath.sh

---

*
-     Which action do you want to perform?
  ...

root@cadf33f01229:/home/docker/RevoMath# R
...
Microsoft R Open 3.2.3
Default CRAN mirror snapshot taken on 2016-01-01
The enhanced R distribution from Microsoft
Visit http://go.microsoft.com/fwlink/?LinkID=722555 for information
about additional features.

Multithreaded BLAS/LAPACK libraries detected. Using 6 cores for math algorithms.
...

**Comment by nuest** [comment]
Thanks for your report! I can confirm the issue - there was a stupid exit code at the beginning of the install function. The build should be available soon - can you please re-try?

https://hub.docker.com/r/nuest/docker-mro/builds/
