### ISSUE TITLE
Document what "quick try" implies

### ISSUE THREAD

**Issue by helmbold** [nuest/mro-docker#7]
> You can use this Docker container to give it a quick try.

I wonder whether this container is production ready or not. "quick try" doesn't sound very trustworthy.

**Comment by nuest** [comment]
I am simply not using it in production myself, but I honestly don't see what speaks against it.

If you trust Docker and MRO separately, then I don't see a reason not to put this in a production environment. Do you have any requirements for such a use that are not met by the container?

**Comment by helmbold** [comment]
Thanks for the reply. No, I had no specific requirement not met by the container. I was just wondering why this container should be only used for a "quick try".
