### ISSUE TITLE
Add image variant including RStudio

### ISSUE THREAD

**Issue by nuest** [nuest/mro-docker#8]
cf. `rocker/rstudio`

**Comment by dsammour** [comment]
Is there any updates regarding this issue? It would quite nice to have an MRO/rstudio docker image. 
Thanks,
Denis

**Comment by nuest** [comment]
Do you have experience with writing `Dockerfile`s ?

I'd be happy to help you build this, but won't be able to get to this myself soon.

Steps:

- start `FROM nuest/mro:3.5.3-verse`
- tag it `3.5.3-rstudio`
- copy over relevant instructions from https://github.com/rocker-org/rocker-versioned/blob/master/rstudio/Dockerfile
